# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/mirrors-pylint
    rev: v2.4.1
    hooks:
      - id: pylint
  - repo: https://github.com/psf/black
    rev: 19.3b0
    hooks:
      - id: black
