language: python
python:
    - "3.6"
    - "3.7"
    - "pypy"
install:
    - "python setup.py install"
script:
    - "make test"
notifications:
    email:
        recipients:
            - "ellisonleao@gmail.com"
